### ISSUE TITLE
Can't install on recent rakudo

### ISSUE THREAD

**Issue by Skarsnik** [sergot/IO-Capture-Simple#7]
==> Testing IO::Capture::Simple
t/stderr.t .................... ok
t/stdout.t .................... ok
===SORRY!=== Error while compiling /root/piko/Discord/.panda-work/1450971440_3/lib/Test/IO/Capture.pm
Malformed parameter
at /root/piko/Discord/.panda-work/1450971440_3/lib/Test/IO/Capture.pm:6
------> nts-stdout-ok (Callable $code, $expected⏏ as Str, $reason = '')

**Comment by sergot** [comment]
Fixed with: https://github.com/sergot/IO-Capture-Simple/pull/8, thanks to @syohex++
